### ISSUE TITLE
Mac Release currently not installable

### ISSUE THREAD

**Issue by Avataw** [StephanHCB/go-generator-cli#16]
The current mac release version seems to be not installable on managed devices. 

It currently does not build a normal, installable application.

**Comment by StephanHCB** [comment]
@Avataw could it be that you have a new Mac, with ARM chip? The matrix build currently only builds amd64 (Intel compatible instruction set).

On a managed device it is quite possible that Rosetta is disabled.

Unfortunately I don't own a Mac, and since MacOS can't be installed in a VM on either Windows or Linux, I have no way to test this.

**Comment by Avataw** [comment]
You are correct, I have an ARM chip :d 
Would it be possible to build an arm version as well?
